export const ADD_INGREDIENT='ADD_INGREDIENT';
export const REMOVE_INGREDIENT='REMOVE_INGREDIENT';
export const CLEAR_INGREDIENTS='CLEAR_INGREDIENTS';
export const SET_INGREDIENTS='SET_INGREDIENTS';

export const MAKE_ORDER_START='MAKE_ORDER_START';
export const MAKE_ORDER_SUCCESS='MAKE_ORDER_SUCCESS';
export const MAKE_ORDER_FAIL='MAKE_ORDER_FAIL';

export const FILTER_ORDERS='FILTER_ORDERS';
export const CALCULATE_ORDERS_STATS='CALCULATE_ORDERS_STATS';
export const SET_ORDERS_FILTERS='SET_ORDERS_FILTERS';

export const AUTH_START='AUTH_START';
export const AUTH_SUCCESS='AUTH_SUCCESS';
export const AUTH_FAIL='AUTH_FAIL';
export const SIGNOUT_START='SIGNOUT_START';
export const SIGNOUT_SUCCESS='SIGNOUT_SUCCESS';
export const SIGNOUT_FAIL='SIGNOUT_FAIL';

export const ADD_ITEM_START='ADD_ITEM_START';
export const ADD_ITEM_SUCCESS='ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAIL='ADD_ITEM_FAIL';
export const ADD_ITEM='ADD_ITEM';
export const REMOVE_ITEM_START='REMOVE_ITEM_START';
export const REMOVE_ITEM_SUCCESS='REMOVE_ITEM_SUCCESS';
export const REMOVE_ITEM_FAIL='REMOVE_ITEM_FAIL';
export const REMOVE_ITEM='REMOVE_ITEM';
export const CLEAR_CART_START='CLEAR_CART_START';
export const CLEAR_CART_SUCCESS='CLEAR_CART_SUCCESS';
export const CLEAR_CART_FAIL='CLEAR_CART_FAIL';
export const CLEAR_CART='CLEAR_CART';
export const REMOVE_CART_ERROR='REMOVE_CART_ERROR';

export const UPDATE_PRICES='UPDATE_PRICES';
export const UPDATE_PRICES_START='UPDATE_PRICES_START';
export const UPDATE_PRICES_SUCCESS='UPDATE_PRICES_SUCCESS';
export const UPDATE_PRICES_FAIL='UPDATE_PRICES_FAIL';
export const CHANGE_ROLE_START='CHANGE_ROLE_START';
export const CHANGE_ROLE_SUCCESS='CHANGE_ROLE_SUCCESS';
export const CHANGE_ROLE_FAIL='CHANGE_ROLE_FAIL';
export const ADD_MENU_ITEM_START='ADD_MENU_ITEM_START';
export const ADD_MENU_ITEM_SUCCESS='ADD_MENU_ITEM_SUCCESS';
export const ADD_MENU_ITEM_FAIL='ADD_MENU_ITEM_FAIL';
export const ADD_MENU_ITEM='ADD_MENU_ITEM';
export const REMOVE_MENU_ITEM_START='REMOVE_MENU_ITEM_START';
export const REMOVE_MENU_ITEM_SUCCESS='REMOVE_MENU_ITEM_SUCCESS';
export const REMOVE_MENU_ITEM_FAIL='REMOVE_MENU_ITEM_FAIL';
export const REMOVE_MENU_ITEM='REMOVE_MENU_ITEM';
export const UPDATE_MENU_ITEM_START='UPDATE_MENU_ITEM_START';
export const UPDATE_MENU_ITEM_SUCCESS='UPDATE_MENU_ITEM_SUCCESS';
export const UPDATE_MENU_ITEM_FAIL='UPDATE_MENU_ITEM_FAIL';
export const UPDATE_MENU_ITEM='UPDATE_MENU_ITEM';
export const SET_BURGER_DATA='SET_BURGER_DATA';
export const CLEAR_BURGER_DATA='CLEAR_BURGER_DATA';