export const ADD_INGREDIENT='ADD_INGREDIENT';
export const REMOVE_INGREDIENT='REMOVE_INGREDIENT';
export const CLEAR_INGREDIENTS='CLEAR_INGREDIENTS';

export const MAKE_ORDER_START='MAKE_ORDER_START';
export const MAKE_ORDER_SUCCESS='MAKE_ORDER_SUCCESS';
export const MAKE_ORDER_FAIL='MAKE_ORDER_FAIL';
export const CLEAR_ORDER_ERROR='CLEAR_ORDER_ERROR';
export const FETCH_ORDERS_START='FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS='FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL='FETCH_ORDERS_FAIL';
export const FILTER_ORDERS='FILTER_ORDERS';
export const SET_FILTERED_ORDERS='SET_FILTERED_ORDERS';
export const CALCULATE_ORDER_STATS='CALCULATE_ORDER_STATS';

export const AUTH_START='AUTH_START';
export const AUTH_SUCCESS='AUTH_SUCCESS';
export const AUTH_FAIL='AUTH_FAIL';
export const AUTH_LOGOUT='AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH='SET_AUTH_REDIRECT_PATH';

export const ADD_CART_ITEM='ADD_CART_ITEM';
export const REMOVE_CART_ITEM='REMOVE_CART_ITEM';
export const UPDATE_CART='UPDATE_APP_CART';
export const CLEAR_CART='CLEAR_CART';